const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Flash,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Exps.left,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Mouse.Acts.SetCursor
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Btn_Bilgi: 0},
	{oynaBtn: 0},
	{Touch: 0},
	{Sprite2: 0},
	{secme3Btn: 0},
	{Sprite3: 0},
	{robi: 0},
	{evBtn: 0},
	{sesBtn: 0},
	{secimkonusma: 0},
	{Audio: 0},
	{tiklanabilme: 0},
	{Flash: 0},
	{robibuton: 0},
	{secme4Btn: 0},
	{secme5Btn: 0},
	{secme6Btn: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{cikolataliP: 0},
	{muzluP: 0},
	{cilekliP: 0},
	{karisikP: 0},
	{pastasecimkonusma: 0},
	{Sprite6: 0},
	{robisunum: 0},
	{robi2: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{robi3: 0},
	{robi4: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{yumurta: 0},
	{Sprite12: 0},
	{un: 0},
	{sut: 0},
	{pastaCesit: 0},
	{Sprite13: 0},
	{rakamlarBtn: 0},
	{Sprite15: 0},
	{silBtn: 0},
	{tamamBtn: 0},
	{problemTxt: 0},
	{cevapTxt: 0},
	{Sprite11: 0},
	{RobiPisirmeEkranTasarimi: 0},
	{Sprite14: 0},
	{RobiPisirmeEkranTasarimi2: 0},
	{pisirBtn: 0},
	{pastakeki: 0},
	{firinyazi: 0},
	{Sprite19: 0},
	{robi5: 0},
	{k5: 0},
	{robi6: 0},
	{robi7: 0},
	{robi8: 0},
	{Browser: 0},
	{robi9: 0},
	{robi9k: 0},
	{robi13: 0},
	{Sprite16: 0},
	{k13: 0},
	{Robi15a: 0},
	{Robi15b: 0},
	{Robi15c: 0},
	{Robi15d: 0},
	{Sprite17: 0},
	{Ev1Btn: 0},
	{Sprite18: 0},
	{bilgiTxt: 0},
	{ev2Btn: 0},
	{Sprite20: 0},
	{blender: 0},
	{Mouse: 0},
	{Sprite21: 0},
	{Spr_Tesekkur: 0},
	{Btn_BilgiButonlari: 0},
	{Txt_Bilgi: 0},
	{SPR_Donut: 0},
	{butonlar: 0},
	{isimler: 0},
	{isim: 0},
	{kackisilik: 0},
	{pastaturu: 0},
	{secilebilir: 0},
	{pastakod: 0},
	{frame_no: 0},
	{grupsayisi: 0},
	{kesirPayda2: 0},
	{cilek: 0},
	{yumurtaSayisi: 0},
	{kesirPayda: 0},
	{aktif: 0},
	{pisirmepayda: 0},
	{pisirmecevap: 0},
	{pisirmepay: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Btn_Bilgi: class extends self.ISpriteInstance {},
	oynaBtn: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	secme3Btn: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	robi: class extends self.ISpriteInstance {},
	evBtn: class extends self.ISpriteInstance {},
	sesBtn: class extends self.ISpriteInstance {},
	secimkonusma: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	robibuton: class extends self.ISpriteInstance {},
	secme4Btn: class extends self.ISpriteInstance {},
	secme5Btn: class extends self.ISpriteInstance {},
	secme6Btn: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	cikolataliP: class extends self.ISpriteInstance {},
	muzluP: class extends self.ISpriteInstance {},
	cilekliP: class extends self.ISpriteInstance {},
	karisikP: class extends self.ISpriteInstance {},
	pastasecimkonusma: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	robisunum: class extends self.ISpriteInstance {},
	robi2: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	robi3: class extends self.ISpriteInstance {},
	robi4: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	yumurta: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	un: class extends self.ISpriteInstance {},
	sut: class extends self.ISpriteInstance {},
	pastaCesit: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	rakamlarBtn: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	silBtn: class extends self.ISpriteInstance {},
	tamamBtn: class extends self.ISpriteInstance {},
	problemTxt: class extends self.ITextInstance {},
	cevapTxt: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	RobiPisirmeEkranTasarimi: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	RobiPisirmeEkranTasarimi2: class extends self.ISpriteInstance {},
	pisirBtn: class extends self.ISpriteInstance {},
	pastakeki: class extends self.ISpriteInstance {},
	firinyazi: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	robi5: class extends self.ISpriteInstance {},
	k5: class extends self.ISpriteInstance {},
	robi6: class extends self.ISpriteInstance {},
	robi7: class extends self.ISpriteInstance {},
	robi8: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	robi9: class extends self.ISpriteInstance {},
	robi9k: class extends self.ISpriteInstance {},
	robi13: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	k13: class extends self.ISpriteInstance {},
	Robi15a: class extends self.ISpriteInstance {},
	Robi15b: class extends self.ISpriteInstance {},
	Robi15c: class extends self.ISpriteInstance {},
	Robi15d: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Ev1Btn: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	bilgiTxt: class extends self.ITextInstance {},
	ev2Btn: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	blender: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Spr_Tesekkur: class extends self.ISpriteInstance {},
	Btn_BilgiButonlari: class extends self.ISpriteInstance {},
	Txt_Bilgi: class extends self.ITextInstance {},
	SPR_Donut: class extends self.ISpriteInstance {},
	butonlar: class extends self.ISpriteInstance {}
}